"""
Map.py — NYC Monthly Crashes Dashboard
=======================================
A Streamlit app that renders an interactive choropleth map of NYC motor vehicle
collisions aggregated by ZIP code and month.

Data source : monthly_crashes_gdf.geojson  (generated by Crashes_EDA.ipynb)
Dependencies: streamlit, geopandas, streamlit-folium, folium

Run locally:
    streamlit run Map.py
"""

import streamlit as st
import geopandas as gpd
from streamlit_folium import st_folium

# --- PAGE CONFIG ---------------------------------------------------------------
# wide layout gives the map more horizontal room
st.set_page_config(layout="wide")
st.title("NYC Monthly Crashes Dashboard")


# --- DATA LOADING --------------------------------------------------------------
@st.cache_data
def load_data() -> gpd.GeoDataFrame:
    """
    Load the pre-built GeoJSON file into a GeoDataFrame.
    @st.cache_data ensures the file is read only once per session,
    avoiding redundant disk reads on every widget interaction.
    """
    return gpd.read_file("monthly_crashes_gdf.geojson")


monthly_crashes_gdf = load_data()


# --- USER INTERFACE (DROPDOWNS) ------------------------------------------------
# Place the two dropdowns side-by-side using Streamlit columns
col1, col2 = st.columns(2)

with col1:
    # Year selector — sorted ascending so the list reads chronologically
    years = sorted(monthly_crashes_gdf["YEAR"].unique())
    selected_year = st.selectbox("1. Choose a Year", years)

with col2:
    # Month selector — only shows months that exist for the chosen year,
    # preventing empty map states from invalid year/month combinations
    available_months = sorted(
        monthly_crashes_gdf[monthly_crashes_gdf["YEAR"] == selected_year]["MONTH"].unique()
    )
    selected_month = st.selectbox("2. Choose a Month", available_months)


# --- DATA FILTERING ------------------------------------------------------------
# Subset to exactly the year+month the user selected
filtered_gdf = monthly_crashes_gdf[
    (monthly_crashes_gdf["YEAR"]  == selected_year) &
    (monthly_crashes_gdf["MONTH"] == selected_month)
]


# --- MAP RENDERING -------------------------------------------------------------
if not filtered_gdf.empty:
    st.write(f"Showing data for **{selected_year} — {selected_month}**")

    # explore() builds a Folium choropleth from the GeoDataFrame.
    # - column      : the variable that drives the colour scale
    # - tooltip     : fields shown when hovering over a ZIP code polygon
    # - cmap        : Yellow → Orange → Red colour ramp (low → high crash volume)
    # - style_kwds  : polygon styling (opacity, border weight/colour)
    m = filtered_gdf.explore(
        column="Monthly crashes",
        tooltip=["ZIP CODE", "Monthly crashes", "Monthly injuries", "Monthly deaths"],
        cmap="YlOrRd",
        style_kwds={"fillOpacity": 0.6, "weight": 1, "color": "grey"},
        legend=True,
    )

    # Render the Folium map inside the Streamlit app
    st_folium(m, width=1000, height=600)

else:
    st.warning("No data available for this selection.")
